### ISSUE TITLE
Add support for IPv4 and CIDR IP ranges and other features

### ISSUE THREAD

**Issue by bawzz234** [Wrentch/GO-Port-scanner#1]
Hello, 

Thanks for creating this app. I was actually looking for a GOlang's port scanner. Simply because of its excellent performance on threads and accuracy. And the speed is incomparable to other languages. 

It would be very useful if you could add these features:

- [ ] Add support for ipv4 and CIDR Ranges. For example:
123.123.12.23-123.123.12.255
123.123.0.0/17

So the command may look like this for IPv4 Ranges:
**scanner.exe -threads=100 -protocol=tcp -host=123.123.12.23-123.123.12.255 -ports=8080,80,443**
and if CIDR used:
**scanner.exe -threads=500 -protocol=tcp -host=123.123.0.0/17 -ports=8080,80,443**
  if both type of ranges is not possible to add then IPv4 is most preferable.

- [x] Add function to save the open port results to a file (IP:Port) format.
For example, the command used:
**scanner.exe -threads=100 -protocol=tcp -host=123.123.12.23-123.123.12.255 -ports=8080,80,443 -output=result.txt**
if the open ports found from IPs they will be saved as IP:Port format. If multiple open ports found from same IP, then they will be added in new line like this:
123.123.12.132:80
123.123.12.132:8080

- [x] Have option to set ranges of ports. For example:
**-ports=443,80,8080,9000-10000**

- [ ] Have option to select scan method. SYN Scan as default is most preferable. 
- [x] a custom -timeout= option 

Hope you could add this features. There are lots of other port scanners from different languages, but not good ones in golang. These features will surely bring this go app to the top.

Best Regards

**Comment by Wrentch** [comment]
Hello, this is a small weekend project I did for fun. Its not really a cli but I guess I could turn in into one. Im am currently somewhat new golang and am still learning it. I guess I could add some of those features when I get the time even tho maybe not all. Golang is fun to play with so I can see myself doing it. I didnt expect an comment on my repo so this is still somewhat new to me (I mean github). If you have the patience, then sure, I can give it a shot. Thank you for the suggestions.

**Comment by Wrentch** [comment]
Hi, I would only like to ask you to leave a star on the project since I dont feel like putting in the time for nothing. Would be really cool to at least get some stars 😅

**Comment by bawzz234** [comment]
Oh I thought I gave you the star, totally forgot, my bad, just added :)

**Comment by Wrentch** [comment]
"Have option to select scan method. SYN Scan as default is most preferable." What other algorithms would you maybe want implemented. I don't really use port scanners a lot so I kinda need some assistance with this part 😅

**Comment by bawzz234** [comment]
Hello

Thanks for adding other features. I appreciate your hard work on it. 

Could you add CONNECT and TCP scan method as alternative options? And SYN as default will be the best choice. 

And for adding ipv4 ranges, this might help:

https://golang.org/src/net/ip.go

Also this:
https://play.golang.org/p/c0qpmFCK_2

If ipv4 range is too difficult to add, CIDR would be sufficient enough

Best Regards.
